language: c
compiler: gcc
env:
  - OCAML_VERSION=latest
  - RACKET_VERSION=6.0

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us

script: ./tools/update && tools/testruse

