language: c
compiler: gcc
# globals set in CI

before_install:
  - sudo add-apt-repository ppa:avsm/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq ocaml ocaml-native-compilers camlp4-extra opam
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}" #install-racket.sh can't set for us
  - opam init
  - opam install ocamlfind
  - opam install bisect
  - eval `opam config env`
#  - sudo pip install cpp-coveralls


script: ./tools/update && tools/testruse

#after_success:
#  - coveralls --include buildsrc --exclude am --gcov-options '\-lp'


