#!/usr/bin/env bash
# Update Ruse test environment
# By Adriaan Larmuseau

############################
# Function :: Capitalize
# Captilaze a string
############################
function capitalize
{
    local ret=$(echo $1 | tr "[:lower:]" "[:upper:]")
    echo $ret
}

# create RUSE for all
./ruse -c
./ruse -dc

# TODO create ML and SCHEME specific ruse
echo "Done Compiling"

# generate byte code files for all langauges
langarray=( ml scheme )
extarray=(  ml scm )
i=0

# generate byte code for every test
for dir in "${langarray[@]}"; do
    echo -e "\033[1;33m => Parsing ::  $(capitalize $dir)\033[0m"
    for f in test/$dir/*.${extarray[$i]}; do
        echo ">> $f"
        ./ruse -p $f 
        mv *.byte* test/$dir/byte 2> /dev/null
    done
    i=$[i + 1]
done
echo "Done Generating Byte Code"

