#########################################
#     Custom MakeFile                   #
# By Adriaan Larmuseau                  #
#########################################

# make nicer later
#

all:
	gcc invalid_label.c -o invalid_label -I../lib/ -L../lib/ -lruse
